import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import type { MediaStore } from "./ports";

/** Media keys are generated by the API ("share/<id>.png"); anything else is a bug or an attack. */
const KEY_RE = /^[a-z0-9][a-z0-9_-]*(\/[a-z0-9][a-z0-9_-]*)*\.[a-z0-9]+$/i;

export function assertMediaKey(key: string): void {
  if (!KEY_RE.test(key)) throw new Error(`invalid media key: ${key}`);
}

/**
 * Short cache: a card deleted by its owner should disappear from CloudFront soon.
 */
const CACHE_CONTROL = "public, max-age=3600";

export class S3MediaStore implements MediaStore {
  private readonly s3: S3Client;

  constructor(
    private readonly bucket: string,
    region: string,
    s3?: S3Client,
  ) {
    this.s3 = s3 ?? new S3Client({ region });
  }

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertMediaKey(key);
    await this.s3.send(
      new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: bytes, ContentType: contentType, CacheControl: CACHE_CONTROL }),
    );
  }

  async delete(key: string): Promise<void> {
    assertMediaKey(key);
    await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

/** Writes under a local directory (npm run dev, E2E). Served at /media/* by local.ts. */
export class LocalMediaStore implements MediaStore {
  readonly dir: string;

  constructor(dir: string) {
    this.dir = path.resolve(dir);
  }

  private file(key: string): string {
    assertMediaKey(key);
    return path.join(this.dir, ...key.split("/"));
  }

  async put(key: string, bytes: Uint8Array): Promise<void> {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, bytes);
  }

  async delete(key: string): Promise<void> {
    await rm(this.file(key), { force: true });
  }
}

/** In-memory store for tests. */
export class MemoryMediaStore implements MediaStore {
  readonly objects = new Map<string, { bytes: Uint8Array; contentType: string }>();

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertMediaKey(key);
    this.objects.set(key, { bytes, contentType });
  }

  async delete(key: string): Promise<void> {
    this.objects.delete(key);
  }
}
