import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { CopyObjectCommand, DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import type { MediaStore } from "./ports";

/** Media keys are generated by the API ("share/<id>.png"); anything else is a bug or an attack. */
const KEY_RE = /^[a-z0-9][a-z0-9_-]*(\/[a-z0-9][a-z0-9_-]*)*\.[a-z0-9]+$/i;

export function assertMediaKey(key: string): void {
  if (!KEY_RE.test(key)) throw new Error(`invalid media key: ${key}`);
}

/**
 * Short cache: a card deleted by its owner or hidden by moderation (moved out of share/) should
 * disappear from CloudFront and browsers within 5 minutes, without paying for invalidations.
 */
export const MEDIA_CACHE_CONTROL = "public, max-age=300";

const isMissing = (err: unknown) => {
  const e = err as { name?: string; code?: string; $metadata?: { httpStatusCode?: number } } | null;
  return e?.name === "NoSuchKey" || e?.name === "NotFound" || e?.code === "ENOENT" || e?.$metadata?.httpStatusCode === 404;
};

export class S3MediaStore implements MediaStore {
  private readonly s3: S3Client;

  constructor(
    private readonly bucket: string,
    region: string,
    s3?: S3Client,
  ) {
    this.s3 = s3 ?? new S3Client({ region });
  }

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertMediaKey(key);
    await this.s3.send(
      new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: bytes, ContentType: contentType, CacheControl: MEDIA_CACHE_CONTROL }),
    );
  }

  async delete(key: string): Promise<void> {
    assertMediaKey(key);
    await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }

  /** Server-side copy; Content-Type and Cache-Control come along (MetadataDirective COPY). */
  async copy(from: string, to: string): Promise<boolean> {
    assertMediaKey(from);
    assertMediaKey(to);
    try {
      await this.s3.send(new CopyObjectCommand({ Bucket: this.bucket, Key: to, CopySource: `${this.bucket}/${from}` }));
      return true;
    } catch (err) {
      if (isMissing(err)) return false;
      throw err;
    }
  }

  async move(from: string, to: string): Promise<boolean> {
    if (!(await this.copy(from, to))) return false;
    await this.delete(from);
    return true;
  }
}

/** Writes under a local directory (npm run dev, E2E). Served at /media/* by local.ts. */
export class LocalMediaStore implements MediaStore {
  readonly dir: string;

  constructor(dir: string) {
    this.dir = path.resolve(dir);
  }

  private file(key: string): string {
    assertMediaKey(key);
    return path.join(this.dir, ...key.split("/"));
  }

  async put(key: string, bytes: Uint8Array): Promise<void> {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, bytes);
  }

  async delete(key: string): Promise<void> {
    await rm(this.file(key), { force: true });
  }

  async copy(from: string, to: string): Promise<boolean> {
    const source = this.file(from);
    const target = this.file(to);
    await mkdir(path.dirname(target), { recursive: true });
    try {
      await copyFile(source, target);
      return true;
    } catch (err) {
      if (isMissing(err)) return false;
      throw err;
    }
  }

  async move(from: string, to: string): Promise<boolean> {
    if (!(await this.copy(from, to))) return false;
    await this.delete(from);
    return true;
  }
}

/** In-memory store for tests. */
export class MemoryMediaStore implements MediaStore {
  readonly objects = new Map<string, { bytes: Uint8Array; contentType: string }>();

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertMediaKey(key);
    this.objects.set(key, { bytes, contentType });
  }

  async delete(key: string): Promise<void> {
    this.objects.delete(key);
  }

  async copy(from: string, to: string): Promise<boolean> {
    assertMediaKey(to);
    const object = this.objects.get(from);
    if (!object) return false;
    this.objects.set(to, { ...object });
    return true;
  }

  async move(from: string, to: string): Promise<boolean> {
    if (!(await this.copy(from, to))) return false;
    await this.delete(from);
    return true;
  }
}
